
orbs:
  node: circleci/node@4.5.0

version: 2.1
jobs:
  codeql:
    docker:
      - image: 'cimg/base:2021.05'
    steps:
      - checkout: { path: "my-app" } # checkout codebase in own directory, separate from codeql cli bundle so it does not analyze itself
      - node/install
      - run:
          name: Download CodeQL CLI
          command: |
            wget https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-linux64.tar.gz -O codeql-bundle-linux64.tar.gz
            tar xzvf codeql-bundle-linux64.tar.gz
            rm codeql-bundle-linux64.tar.gz
            export PATH=$(pwd)/codeql:$PATH
      - run:
          name: Create CodeQL Database
          command: |
            mkdir codeql-dbs
            ./codeql/codeql database create ./codeql-dbs/repo-db --language=javascript --source-root=./my-app
      - run:
          name: Analyze CodeQL Database
          command: |
            cd codeql && mkdir temp
            ./codeql database analyze ../codeql-dbs/repo-db javascript-code-scanning.qls --format=sarif-latest --output=./temp/results-js.sarif
            cat ./temp/results-js.sarif   

      # - when: 
      #     condition: ${CIRCLE_PULL_REQUEST}
      #     steps:
      #       - run: ./codeql/codeql github upload-results --repository=org/example-app --ref=refs/pull/${CIRCLE_PULL_REQUEST##*/}/head --commit=$CIRCLE_SHA1 --sarif=./codeql/temp/results-js.sarif
      # - unless: 
      #     condition: ${CIRCLE_PULL_REQUEST}
      #     steps: 
      #       - run: ./codeql/codeql github upload-results --repository=org/example-app --ref=refs/heads/${CIRCLE_BRANCH} --commit=$CIRCLE_SHA1 --sarif=./codeql/temp/results-js.sarif

workflows:
  version: 2
  codeql-analysis:
    jobs:
      - codeql